### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by glatiuden** [Huggenguggen/EZMod#7]
```
Heroku to host our application (currently hosting on github at https://huggenguggen.github.io/EZMod/)
```

![image](https://user-images.githubusercontent.com/13434148/171156680-821cc480-b9a9-44a3-8658-a01cbe5b5749.png)

@Huggenguggen @lywich able to check on the link? It's not working on my side.

**Comment by Huggenguggen** [comment]
Hi! can you try the link again? It should be up now. 
https://huggenguggen.github.io/EZMod/
